### ISSUE TITLE
Interface Builder

### ISSUE THREAD

**Issue by gizmosachin** [BigZaphod/Chameleon#15]
Doesn't work with Interface Builder for me. Is this just me?

**Comment by BigZaphod** [comment]
Currently it does not play nice with IB. This needs to be addressed - ideally by someone far more familiar with IB than I am. :)

**Comment by CarterA** [comment]
I've worked quite a bit with IB plugins, and I'll say right now:  this would be hella difficult. That, and Xcode 4 doesn't support IB plugins yet, which indicates (at least to me) that they might be overhauling the plugin system. If they're going to be changing it a lot, it isn't worth the time to try and hack a Chameleon plugin together now.

**Comment by danielkramer** [comment]
Does this help?  Haven't tried it myself

https://github.com/akosma/nib2objc
