### ISSUE TITLE
UIKit does not build in release mode in Xcode4

### ISSUE THREAD

**Issue by jamiepinkham** [BigZaphod/Chameleon#39]
Haven't tried with Xcode3, but building with "release" in Xcode causes many un-resolvable issues.

**Comment by jamiepinkham** [comment]
actually, chameleon doesn't build for 32-bit at all.

**Comment by BigZaphod** [comment]
Are you targeting something earlier than 10.6? Chameleon is 10.6+. I just built it in 32 bit with no problem. We also routinely build in Release mode when we ship Twitterrific for the Mac. I think something else might be wrong?

**Comment by jamiepinkham** [comment]
when i build for 32 bit mode i get a ton of "incompatible type for argument 1 of initWithFrame:" for classes like UIWindow, UIImageView, etc.. very strange.

**Comment by jamiepinkham** [comment]
the same issue occurs in your sample projects included with the repo

**Comment by jamiepinkham** [comment]
Ok.  I've figured it out.

The reason a 32-bit build doesn't work, but a 64-bit build does is that in 64-bit, NSRect is defined to CGRect, so it works.  But in 32-bit it all falls apart.

Since, in 32-bit, NSRect != CGRect and initWithFrame returns an id, the compiler is forced to find a matching signature from your available imports.  Since AppKit is include, NSView's initWithFrame is resolved.  Which takes an NSRect.

The solution is to add a -(id)initWithCGRect:(CGRect) to UIView, and call that instead of UIView's initWithFrame, the implementation is simply just calling initWithRect.

I'll fork and do a pull request with the fix.

**Comment by BigZaphod** [comment]
It sounds like something is different when you target for 32 bit, and the error about initWithFrame: tells me that probably AppKit headers are being included (maybe in a precompiled header like your .pch or something?) when they shouldn't be. Care needs to be taken when and where AppKit headers are included because of the naming conflicts with some selectors such as initWithFrame: which takes an NSRect for AppKit, but a CGRect for Chameleon/UIKit.

That said, I don't see it happening for me when I change the UIKit project's target from 64 to 32, so I don't know why it'd be different for you unless the project files have been modified or there's some kind of local configuration either avoiding the problem on my end or causing it on yours. I do know that many people have been building and using Chameleon and this is the first I've heard of this problem (but of course others may just not have noticed it).

**Comment by jamiepinkham** [comment]
Well, it happens in your samples that you include in the repo, so I think it might be more common than you think.

**Comment by lvandal** [comment]
I have the same issues when trying to archive in either 32 or 64 bits.

UIImageView *background = [[UIImageView alloc] initWithFrame:[self frame]];

Sending 'CGRect' (aka 'struct CGRect') to parameter of incompatible type 'NSRect' (aka 'struct _NSRect')

**Comment by lvandal** [comment]
Moreover, the MultiApple sample will fail to compile when archiving because of the same issue:

self.view = [[[UIView alloc] initWithFrame:CGRectMake(0,0,320,460)] autorelease];

Incompatible type for argument 1 of 'initWithFrame:'

**Comment by joshaber** [comment]
fwiw, you can get around these errors by casting the result of +alloc:

``` objective-c
self.view = [[(UIView *)[UIView alloc] initWithFrame:CGRectMake(0,0,320,460)] autorelease];
```

**Comment by lvandal** [comment]
I've fixed the issue by replacing:

#import &lt;Cocoa/Cocoa.h&gt;

with: 

#import &lt;Foundation/Foundation.h&gt;

in the .pch file.

**Comment by seqoy** [comment]
<b>Here are some answers:</b>
Before Leopard, <code>NSRect</code> and <code>CGRect</code> were completely different types. Apple took the opportunity provided by the transition to 64-bit to eliminate the discrepancy. But this change could break binary compatibility, so it couldn't be done across the board for 32-bit code.

<code>NSRect</code> is the same type as <code>CGRect</code> if building for iOS, for a <b>64-bit Mac architecture</b>, or a <b>32-bit Mac architecture</b> with the macro <code>NS_BUILD_32_LIKE_64</code> defined as <code>1</code> at the command line or in a prefix header.

If you check the file <code>NSGeometry.h</code> you will see the conditional <code>#if **LP64** || TARGET_OS_EMBEDDED || TARGET_OS_IPHONE || TARGET_OS_WIN32 || NS_BUILD_32_LIKE_64</code>.

Ok, pretty good pal, but enough of this bullshit. How do we solve the problem???

We can set our target to <b>64 bit</b>, or if you prefer set the target as <b>32 bit</b> and define the <code>NS_BUILD_32_LIKE_64</code> as <code>1</code> in our XCode Project.

If you like the second option, edit your <code>.pch</code> file <i>(find by .pch on XCode)</i> and include this line:<pre>#define NS_BUILD_32_LIKE_64 1</pre>
