### ISSUE TITLE
does the UITableViewCell subviews receive events?

### ISSUE THREAD

**Issue by xfer** [BigZaphod/Chameleon#48]
I was testing the framework with a basic application : a table view with some cells. The UITableView works great! No memory issues, scrolling works like expected, etc. But the UITableViewCell looks problematic, I’ve added a  button, set the target/action and nothing happened. Worse, the "down state" of the button was propagated to the next selected cell (looks like the button didn’t receive a "touch up" event, and never had a chance to redraw / update itself).

Then, I looked into UIGestureRecognizers, but they are mostly no-op currently, so I’m out of ideas, except for asking : should I do something special to UIButtons work inside UITableViewCells or isn’t implemented yet?

**Comment by joshaber** [comment]
Try adding the button to the UITableViewCell's contentView instead of to the UITableViewCell directly.

**Comment by xfer** [comment]
Oh, thanks, it’s working!
(And now I feel stupid, there is a contentView in iOS API)
