### ISSUE TITLE
dyld: Library not loaded: @executable_path/

### ISSUE THREAD

**Issue by seqoy** [BigZaphod/Chameleon#55]
I'm fighting for a while with this error message when running my App with the Chameleon project:

<pre>
dyld: Library not loaded: @executable_path/../Frameworks/UIKit.framework/Versions/A/UIKit
  Referenced from: /Users/Documents/Projects/libs/Chameleon/Examples/BigApple/build/Debug/CME.app/Contents/MacOS/CME
  Reason: image not found
</pre>

**Comment by seqoy** [comment]
Finally I got my answer. I did miss to include the framework into the binary. To do that, go to your target configuration and created (or edit) the build phase <b>Copy Frameworks</b>, drag the <b>UIKit.framework</b> file inside and rebuild your binary. Should work.

**Comment by BigZaphod** [comment]
It looks like the Chameleon framework is not being included in your app bundle. You'll need to add a copy phase to your target in Xcode that copies the Chameleon framework into your bundle's Frameworks folder. This might be a place to start: http://developer.apple.com/library/mac/#documentation/MacOSX/Conceptual/BPFrameworks/Tasks/CreatingFrameworks.html

**Comment by seqoy** [comment]
Thank you!! Is working now.
