### ISSUE TITLE
UITableViewStyleGrouped implementation

### ISSUE THREAD

**Issue by neozenith** [BigZaphod/Chameleon#63]
Dear Illusion of Chameleons,

(Side Note: http://wiki.answers.com/Q/What_is_the_Name_for_a_group_of_chameleons)

You are such a tease. All this beautiful UIKit on OSX and no UITableViewStyleGrouped implementation for UITableView.

Just wondering on a development status on this before diving in to build this functionality myself.

If implementing it isn't in your foreseeable future is there anything other than the Coding Style Guidelines I should be aware of before tackling this?

Kind Regards
-neozenith

**Comment by BigZaphod** [comment]
I haven't been watching the forks very carefully lately, so it's possible someone has started work on this - but I have not and don't anticipate doing so myself.
